#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();
signals:
    void dazichecked();
private slots:
    void on_Edit_input_textEdited(const QString &arg1);
    void updata_hanzi();
    void on_len_word_returnPressed();

    void on_ord_words_returnPressed();

    void on_extime_words_returnPressed();

    void on_accura_words_returnPressed();

    void on_resetButton_clicked();

    void on_check_true_stateChanged(int arg1);

    void on_check_false_stateChanged(int arg1);

    void on_siziEdit_textEdited(const QString &arg1);

    void on_disruptbutton_clicked();

private:
    Ui::MainWindow *ui;
    int num_words[402];//dei太生僻了，排除
    int flagtrue=1;
    int flagfalse=0;
    int flagtoomanyword=0;
    int batch;
    int num_batch;
    int current1;
    int num_true;
    int num_sum;
    int current_word;
    int Number =402;
    int accuracyrate=80;
    int extime=3;
    int dida=0;
    QString words[402]={
        "aa",
        "ai",
        "an",
        "ah",
        "ao",
        "ee",
        "ei",
        "en",
        "er",
        "oo",
        "ou",
        "ba",
        "bd",
        "bj",
        "bh",
        "bc",
        "bw",
        "bf",
        "bg",
        "bi",

        "bm",
        "bn",
        "bp",
        "bb",
        "bk",
        "bo",
        "bu",
        "ca",
        "cd",
        "cj",
        "ch",
        "cc",
        "ce",
        "cf",
        "cg",
        "ci",
        "cs",
        "cz",
        "cu",
        "cr",
        "cv",
        "cy",
        "co",

        "da",
        "dd",
        "dj",
        "dh",
        "dc",
        "de",
        "dg",
        "di",
        "dx",
        "dm",
        "dn",
        "dp",
        "dk",
        "dq",
        "ds",
        "dz",
        "du",
        "dr",
        "dv",

        "dy",
        "do",
        "fa",
        "fj",
        "fh",
        "fw",
        "ff",
        "fg",
        "fo",
        "fz",
        "fu",
        "ga",
        "gd",
        "gj",
        "gh",
        "gc",
        "ge",
        "gw",
        "gf",
        "gg",

        "gs",
        "gz",
        "gu",
        "gx",
        "gk",
        "gr",
        "gl",
        "gv",
        "gy",
        "go",
        "ha",
        "hd",
        "hj",
        "hh",
        "hc",
        "he",
        "hw",
        "hf",
        "hg",
        "hs",

        "hz",
        "hu",
        "hx",
        "hk",
        "hr",
        "hl",
        "hv",
        "hy",
        "ho",
        "ji",
        "jx",
        "jm",
        "jl",
        "jn",
        "jp",
        "jb",
        "jk",
        "js",
        "jq",
        "ju",

        "jr",
        "jt",
        "jy",
        "ka",
        "kd",
        "kj",
        "kh",
        "kc",
        "ke",
        "kf",
        "kg",
        "ks",
        "kz",
        "ku",
        "kx",
        "kk",
        "kr",
        "kl",
        "kv",
        "ky",

        "ko",
        "la",
        "ld",
        "lj",
        "lh",
        "lc",
        "le",
        "lw",
        "lg",
        "li",
        "lx",
        "lm",
        "ll",
        "ln",
        "lp",
        "lb",
        "lk",
        "lq",
        "lo",
        "ls",

        "lz",
        "lu",
        "lr",
        "ly",
        "lo",
        "lv",
        "lt",
        "ma",
        "md",
        "mj",
        "mh",
        "mc",
        "me",
        "mw",
        "mf",
        "mg",
        "mi",
        "mm",
        "mn",
        "mp",
        "mb",

        "mk",
        "mq",
        "mo",
        "mz",
        "mu",
        "na",
        "nd",
        "nj",
        "nh",
        "nc",
        "ne",
        "nw",
        "nf",
        "ng",
        "ni",
        "nm",
        "nl",
        "nn",
        "np",
        "nb",

        "nk",
        "nq",
        "ns",
        "nu",
        "nr",
        "no",
        "nv",
        "nt",
        "pa",
        "pd",
        "pj",
        "ph",
        "pc",
        "pw",
        "pf",
        "pg",
        "pi",
        "pm",
        "pn",
        "pp",

        "pb",
        "pk",
        "po",
        "pz",
        "pu",
        "qi",
        "qx",
        "qm",
        "ql",
        "qn",
        "qp",
        "qb",
        "qk",
        "qs",
        "qq",
        "qu",
        "qr",
        "qt",
        "qy",
        "rj",

        "rh",
        "rc",
        "re",
        "rf",
        "rg",
        "ri",
        "rs",
        "rz",
        "ru",
        "rr",
        "rv",
        "ry",
        "ro",
        "sa",
        "sd",
        "sj",
        "sh",
        "sc",
        "se",
        "sf",

        "sg",
        "si",
        "ss",
        "sz",
        "su",
        "sr",
        "sv",
        "sy",
        "so",
        "ta",
        "td",
        "tj",
        "th",
        "tc",
        "te",
        "tg",
        "ti",
        "tm",
        "tn",
        "tp",

        "tk",
        "ts",
        "tz",
        "tu",
        "tr",
        "tv",
        "ty",
        "to",
        "wa",
        "wd",
        "wj",
        "wh",
        "ww",
        "wf",
        "wg",
        "wo",
        "wu",
        "xi",
        "xx",
        "xm",

        "xl",
        "xn",
        "xp",
        "xb",
        "xk",
        "xs",
        "xq",
        "xu",
        "xr",
        "xt",
        "xy",
        "ya",
        "yj",
        "yh",
        "yc",
        "ye",
        "yi",
        "yb",
        "yk",
        "yo",

        "ys",
        "yz",
        "yu",
        "yr",
        "yt",
        "yy",
        "za",
        "zd",
        "zj",
        "zh",
        "zc",
        "ze",
        "zw",
        "zf",
        "zg",
        "zi",
        "zs",
        "zz",
        "zu",
        "zr",

        "zv",
        "zy",
        "zo",
        "ia",
        "id",
        "ij",
        "ih",
        "ic",
        "ie",
        "if",
        "ig",
        "ii",
        "is",
        "iz",
        "iu",
        "ix",
        "ik",
        "ir",
        "il",
        "iv",

        "iy",
        "io",
        "ua",
        "ud",
        "uj",
        "uh",
        "uc",
        "ue",
        "uf",
        "ug",
        "ui",
        "uz",
        "uu",
        "ux",
        "uk",
        "ur",
        "ul",
        "uv",
        "uy",
        "uo",

        "va",
        "vd",
        "vj",
        "vh",
        "vc",
        "ve",
        "vf",
        "vg",
        "vi",
        "vs",
        "vz",
        "vu",
        "vx",
        "vk",
        "vr",
        "vl",
        "vv",
        "vy",
        "vo"
    };
    QString hanzi[402]={
        "啊",
        "爱",
        "安",
        "昂",
        "奥",
        "鹅",
        "诶",
        "嗯",
        "二",
        "哦",
        "欧",
        "爸",
        "白",
        "班",
        "帮",
        "包",
        "被",
        "本",
        "崩",
        "比",

        "边",
        "表",
        "别",
        "宾",
        "并",
        "播",
        "不",
        "擦",
        "才",
        "残",
        "苍",
        "草",
        "测",
        "岑",
        "层",
        "词",
        "从",
        "凑",
        "粗",
        "窜",
        "催",
        "存",
        "错",

        "大",
        "待",
        "但",
        "当",
        "到",
        "的",
        "等",
        "帝",
        "嗲",
        "电",
        "掉",
        "爹",
        "定",
        "丢",
        "动",
        "兜",
        "毒",
        "断",
        "对",

        "顿",
        "多",
        "发",
        "反",
        "方",
        "非",
        "分",
        "锋",
        "佛",
        "否",
        "付",
        "嘎",
        "该",
        "感",
        "刚",
        "高",
        "个",
        "给",
        "跟",
        "更",

        "工",
        "狗",
        "故",
        "瓜",
        "怪",
        "关",
        "光",
        "贵",
        "滚",
        "国",
        "哈",
        "海",
        "寒",
        "航",
        "好",
        "贺",
        "黑",
        "很",
        "哼",
        "红",

        "后",
        "湖",
        "化",
        "坏",
        "换",
        "黄",
        "灰",
        "混",
        "或",
        "机",
        "家",
        "建",
        "将",
        "叫",
        "姐",
        "进",
        "经",
        "窘",
        "就",
        "据",

        "卷",
        "绝",
        "君",
        "咖",
        "开",
        "看",
        "抗",
        "考",
        "可",
        "肯",
        "坑",
        "空",
        "口",
        "哭",
        "夸",
        "块",
        "宽",
        "狂",
        "亏",
        "困",

        "扩",
        "啦",
        "来",
        "蓝",
        "狼",
        "老",
        "了",
        "类",
        "冷",
        "里",
        "俩",
        "连",
        "两",
        "聊",
        "列",
        "林",
        "领",
        "六",
        "咯",
        "龙",

        "楼",
        "路",
        "乱",
        "论",
        "罗",
        "绿",
        "略",
        "妈",
        "买",
        "满",
        "忙",
        "毛",
        "么",
        "没",
        "们",
        "萌",
        "米",
        "面",
        "秒",
        "灭",
        "民",

        "名",
        "谬",
        "末",
        "某",
        "目",
        "那",
        "奶",
        "男",
        "囊",
        "脑",
        "呢",
        "内",
        "嫩",
        "能",
        "你",
        "年",
        "娘",
        "鸟",
        "捏",
        "您",

        "宁",
        "牛",
        "弄",
        "怒",
        "暖",
        "诺",
        "女",
        "虐",
        "爬",
        "拍",
        "盘",
        "胖",
        "跑",
        "陪",
        "喷",
        "碰",
        "屁",
        "片",
        "票",
        "暼",

        "品",
        "平",
        "破",
        "剖",
        "仆",
        "起",
        "恰",
        "钱",
        "强",
        "桥",
        "且",
        "亲",
        "请",
        "穷",
        "求",
        "去",
        "全",
        "却",
        "群",
        "然",

        "让",
        "绕",
        "热",
        "人",
        "扔",
        "日",
        "容",
        "肉",
        "如",
        "软",
        "瑞",
        "润",
        "若",
        "撒",
        "赛",
        "三",
        "桑",
        "扫",
        "色",
        "森",

        "僧",
        "四",
        "送",
        "搜",
        "诉",
        "算",
        "随",
        "孙",
        "锁",
        "他",
        "台",
        "谈",
        "躺",
        "套",
        "特",
        "疼",
        "体",
        "天",
        "条",
        "贴",

        "听",
        "同",
        "头",
        "图",
        "团",
        "退",
        "吞",
        "拖",
        "哇",
        "外",
        "万",
        "往",
        "为",
        "问",
        "翁",
        "我",
        "物",
        "西",
        "下",
        "现",

        "想",
        "小",
        "些",
        "新",
        "星",
        "熊",
        "修",
        "许",
        "选",
        "学",
        "寻",
        "压",
        "言",
        "阳",
        "要",
        "也",
        "以",
        "因",
        "英",
        "哟",

        "用",
        "有",
        "于",
        "元",
        "月",
        "运",
        "咋",
        "在",
        "咱",
        "脏",
        "早",
        "则",
        "贼",
        "怎",
        "增",
        "子",
        "总",
        "走",
        "组",
        "钻",

        "最","尊","作","茶","拆","产","常","超","车","尘","成","吃","虫","筹","出","歘","踹","传","创","吹",

        "纯","戳","沙","晒","山","上","少","设","神","生","是","首","书","刷","帅","栓","双","水","顺","说",

        "炸","摘","站","章","找","这","真","正","之","中","周","主","抓","拽","转","装","追","准","桌"
    };
};
#endif // MAINWINDOW_H
